version: 2.1

orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.1.4

workflows:
  build:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - "16.15"
                - "14.19"
                - "12.13"
          filters:
            branches:
              only:
                - circleci

      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci
      
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          update-description: true

